### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Dru99** [PServerCMS/SROUnique#7]
Problem with adding the module 

Additional information:
TypeError
File:
/var/www/page/vendor/p-server-cms/sro-unique/src/View/Helper/KillHistoryCharacter.php:29
Message:
Argument 1 passed to PServerCMS\SROUnique\View\Helper\KillHistoryCharacter::__invoke() must implement interface GameBackend\Entity\Game\CharacterInterface, array given

this while trying to view the character page.  

note: i have added the > 10 last unique kills to the sidebar and working fine 👍 
but this ones. 
<?= $this->uniqueKillHistoryCharacterPServerSROUnique([Character], [limit]) ?>
<?= $this->characterEachUniquePointsPServerSROUnique([Character], [limit]) ?>
tried to add the lines to inventory-view but fail with this error

**Comment by kokspflanze** [comment]
@Dru99 you have to give a variable with a object type of `GameBackend\Entity\Game\CharacterInterface`, like on the player-detail page you have that object

**Comment by kokspflanze** [comment]
```twig
 {{ characterEachUniquePointsPServerSROUnique(character) }}
 {{ uniqueKillHistoryCharacterPServerSROUnique(character) }}
```
just add that to your p-server-ranking/character/index.twig file, best way would be a overwrite

**Comment by Dru99** [comment]
>  {{ characterEachUniquePointsPServerSROUnique(character) }}
>  {{ uniqueKillHistoryCharacterPServerSROUnique(character) }}
> just add that to your p-server-ranking/character/index.twig file, best way would be a overwrite
this worked thanks for your answer.
i have 1 more question ( but its about the ranking ) not the SROUnique 
i have viewed the item plus for the Inventory items. i there way for sox items to view the icon of sox ( not the normal icon ) right now the sox items shown as nornal items 

thanks

**Comment by kokspflanze** [comment]
@Dru99 you have all colns you need to know if the item is sox, so where is the problem?

**Comment by Dru99** [comment]
i didn't get you right now ( CMS ) allow shown sox items ? icons or i have to modify it ? 
here is explain what i need 
image https://gyazo.com/147893e376f67f513098fa90930def23
the shield here is Sox item ( why didn't show it's sox icon ? ) or even show the item type ( seal of x )

**Comment by kokspflanze** [comment]
you have to modify it, like you need.

i think you have to use https://github.com/kokspflanze/GameBackend/blob/master/src/GameBackend/Entity/SRO/Shard/RefItem.php#L227

to know if its sox, or not. the basic ranking-module is for more than sro, and not all games have smth like that, so its not added
